### ISSUE TITLE
[BUG] Accent color not applied to Plank

### ISSUE THREAD

**Issue by amminadabz** [Ultramarine-Linux/ultramarine#10]
**Describe the bug**
Accent color is not respected by Plank in Pantheon.

**To Reproduce**
1. Observe: the dock indicators under icons are orange.
2. Go to Appearance under esktop in Switchboard and change the accent color.
3. Behold the dock once more. It is still orange.

**Expected behavior**
Something other than orange. Blue I could understand. But orange? No.

**Screenshots**
![Screenshot from 2022-08-19 20 52 11](https://user-images.githubusercontent.com/51542239/185724761-2056e15d-f471-44f4-aa4d-bf4bc01ec25d.png)

**Desktop (please complete the following information):**
 - OS: Ultramarine Linux Pantheon Edition
 - Version 36

**Additional context**
It might actually be pink

**Comment by nothingneko** [comment]
Plank does not actually apply the accent colour
