### ISSUE TITLE
[BUG] Found some issues with the development KDE Plasma ISO

### ISSUE THREAD

**Issue by cig0** [Ultramarine-Linux/ultramarine#13]
**Describe the bug**

Hi,

I gave `plasma-x86_64` a try (https://github.com/Ultramarine-Linux/build-scripts/actions/runs/3231389756/jobs/5291483988#logs), and found a few issues during the install process and later on while using the system.

I tested this build on a VM using QEMU + KVM + libvirt.

**Screenshots**

_**When booting the image I got this error:**_

![Screenshot_20221105_181743](https://user-images.githubusercontent.com/394089/200193707-0fa42a5c-fd19-44de-9811-f41ddf2b8849.png)

The same thing happens with the Pantheon ISO (the other one I briefly checked). While I haven't tried with the other two images, it seems this is shared across all of them. Maybe some typo with the Dracut scripts?

_**Upon reaching the desktop:**_

![Screenshot_20221105_181826](https://user-images.githubusercontent.com/394089/200193922-4b2862aa-92f7-4aee-a82d-481a0acdce2e.png)

_**There´re no other languages available to choose from:**_

![Screenshot_20221105_182105](https://user-images.githubusercontent.com/394089/200193982-ca7e8473-a7a5-4147-b34d-e13d7a8a3cfd.png)

_**Upon booting the newly installed system:**_

![Screenshot_20221105_182908](https://user-images.githubusercontent.com/394089/200194092-9d8f077c-4e17-4f18-9037-4307ffe17fcb.png)

_**Widgets and notifications will pop up in the left-top corner:**_

![Screenshot_20221105_183217](https://user-images.githubusercontent.com/394089/200194102-2e09cef5-2b9f-4567-aba4-95329b671926.png)

A few observations here:

- I see you guys use Latte dock here; IME this glitch happens when the Plasma panel holding the system tray is missing or hidden
- I already changed the screen resolution (no issues there)
- From now on the system will be fully updated (as you can see in the screenshot)

_**Not strictly a bug: the transparent background makes it hard to read the list of pinned directories in Dolphin**_

![Screenshot_20221105_190124](https://user-images.githubusercontent.com/394089/200194380-c499c728-9359-4a5c-b58d-e14064646571.png)

_**Clicking on the application's widget will make the menu cover the widget:**_

![Screenshot_20221105_190200](https://user-images.githubusercontent.com/394089/200194667-4bdf53bf-4b30-465e-b806-0a196ba28abb.png)

_**Layouts:**_

The default, My Layout and Ultramarine layouts replicate the same (official?) layout

![image](https://user-images.githubusercontent.com/394089/200194736-7d1a41c3-3fd9-4ae9-b4e3-fecdb95c3d3c.png)

_**When clicking on the application widget, the menu will pop up in the top-left corner:**_

(Pretty much the same issue described above)

![image](https://user-images.githubusercontent.com/394089/200194829-55be86be-63af-451a-9beb-e35145871806.png)

_**Repos refresh error:**_

On a subsequent `dnf update --refresh`:

![image](https://user-images.githubusercontent.com/394089/200194917-867efbbc-c16b-412f-be09-d495190871be.png)

_That's all!_

**Comment by korewaChino** [comment]
This seems to be a bug related to `latte-dock`, which is now abandoned. We will be packaging a git build to work around  this issue.

**Comment by korewaChino** [comment]
fixed in latte dock patch
