### ISSUE TITLE
Remove duplicate apps

### ISSUE THREAD

**Issue by KennyDevT** [Ultramarine-Linux/ultramarine#14]
**Is your feature request related to a problem? Please describe.**
Some apps have straight up duplicates or not needed 
example: htop is not needed since the system monitor exist or the fact that terminal is installed but console is also installed. The last example is blivet-gui being installed when disks is also installed.

**Describe the solution you'd like**
just remove them and keep the gnome default

**Comment by korewaChino** [comment]
`bilvet-gui` is **required** for Anaconda to function and do partitioning. and `htop` is included in mind for terminal users.

**Comment by lleyton** [comment]
We should resolve this (somehow,) been confusing users... also Terminal and Console are both installed

**Comment by lleyton** [comment]
@korewaChino would it be more preferable to ship Terminal or Console?

**Comment by korewaChino** [comment]
Terminal.

**Comment by pisekpiskovec** [comment]
There's also gedit and GNOME Text Editor preinstalled and two Screenshot apps (Budgie Screenshot and GNOME Screenshot.

**Comment by lleyton** [comment]
@pisekpiskovec Which variant of UM is that on?

**Comment by pisekpiskovec** [comment]
Ultramarine 37 Budgie

**Comment by nothingneko** [comment]
This appears to be resolved in UM39
