### ISSUE TITLE
No checksums for Ultramarine 37 ISOs

### ISSUE THREAD

**Issue by andrewpacific** [Ultramarine-Linux/ultramarine#15]
The instructions say to check the checksum but unlike the version 36 page there is no checksums , I can't find them anywhere.

https://ultramarine-linux.org/download/

https://repos.fyralabs.com/isos/ultramarine/37/ultramarine-pantheon-x86_64-20221230.iso

I assume this is safe to use?

A confirmed safe checksum would be awesome, ultramarine looks like a great distribution.

**Comment by andrewpacific** [comment]
My SHA256 checksum is:

https://repos.fyralabs.com/isos/ultramarine/37/ultramarine-pantheon-x86_64-20230106.iso

e56c57be4de247bf03f4f43b90f583022a858eb34c6edc8b6f92db9ba44f6714

**Comment by andrewpacific** [comment]
A new ISO was uploaded in the last few minutes:

https://repos.fyralabs.com/isos/ultramarine/37/ultramarine-pantheon-aarch64-20230106.iso

**Comment by lleyton** [comment]
Yup! Preparing for a new (minor) release. I'll add checksums to the site in a bit.

**Comment by lleyton** [comment]
Should be on the site now!
