### ISSUE TITLE
[FEATURE REQUEST]

Distrobuilder by LXD

### ISSUE THREAD

**Issue by OpenOS-Project-Creator-Founder** [Ultramarine-Linux/ultramarine#16]
[To allow UltramarineLinux to Build & Package itself as LXC/LXD Container.]

Using the squashfs from UltramarineLinux Build scripts to pipe through to Distrobuilder. 

Also, other use cases are to package this LXC/LXD container in the ISO end-users/developers download & install. This would allow for developers to have a development container which they can use btrfs snapshots/subvolumes to test things locally.

Other use cases are also possible.

https://github.com/lxc/distrobuilder

**Comment by rmnscnce** [comment]
Ultramarine Linux (further referred to as "Distro") is a Linux distribution based on Fedora Linux (further referred to as "Base Distro") aimed for use on desktop computers. Shall anyone want to develop their software targeting the Distro, they can use any kind of Base Distro containers with collection of software provided through our our repositories which can be added separately as needed. Not to mention, there's also the ability to just boot into a dedicated installation of the Distro shall they opt to test things on their machines locally.

Additionally, installation media sizes matter a lot to us. Simply including a container image inside our installation medias would bump up the size by a considerable amount, which is unacceptable.

Feel free to ask further if you need something clarified.

**Comment by OpenOS-Project-Creator-Founder** [comment]
> Ultramarine Linux (further referred to as "Distro") is a Linux distribution based on Fedora Linux (further referred to as "Base Distro") aimed for use on desktop computers. Shall anyone want to develop their software targeting the Distro, they can use any kind of Base Distro containers with collection of software provided through our our repositories which can be added separately as needed. Not to mention, there's also the ability to just boot into a dedicated installation of the Distro shall they opt to test things on their machines locally.
> 
> Additionally, installation media sizes matter a lot to us. Simply including a container image inside our installation medias would bump up the size by a considerable amount, which is unacceptable.
> 
> Feel free to ask further if you need something clarified.

Please take a look at what I have explained through some git issues with references to others.

https://github.com/ashos/ashos/issues/121

**Comment by rmnscnce** [comment]
Could you please expand on it? I saw things about system recovery, though I don't know how that relates to shipping a container image inside the installation media. And of course, it would considerably bump up the installation media, which is something we would really like to avoid doing.

**Comment by OpenOS-Project-Creator-Founder** [comment]
> Could you please expand on it? I saw things about system recovery, though I don't know how that relates to shipping a container image inside the installation media. And of course, it would considerably bump up the installation media, which is something we would really like to avoid doing.

If you're aware of KDE Neon with it's "editions"...

I have tried to explain it here...

https://github.com/ashos/ashos/issues/120

**Comment by rmnscnce** [comment]
If what you are trying to say is for us to have an immutable edition with the ability to switch channels, we already have OSTree on that, which have yielded great results based on several runs of our internal testing.

**Comment by OpenOS-Project-Creator-Founder** [comment]
> If what you are trying to say is for us to have an immutable edition with the ability to switch channels, we already have OSTree, which have yielded great results based on several runs of our internal testing.

This one?

https://github.com/dbnicholson/deb-ostree-builder

**Comment by korewaChino** [comment]
> > If what you are trying to say is for us to have an immutable edition with the ability to switch channels, we already have OSTree, which have yielded great results based on several runs of our internal testing.
> 
> This one?
> 
> https://github.com/dbnicholson/deb-ostree-builder

??????????

https://github.com/coreos/rpm-ostree

**Comment by windowsboy111** [comment]
Ultramarine Linux is a distribution based on Fedora which uses RPM packages, not DEB.

**Comment by OpenOS-Project-Creator-Founder** [comment]
> Ultramarine Linux is a distribution based on Fedora which uses RPM packages, not DEB.


I am aware ostree is "Agnostic"?...


https://github.com/coreos/rpm-ostree

https://invent.kde.org/plasma/discover/-/merge_requests/109

https://discussion.fedoraproject.org/t/rpm-ostree-support-in-kde-discover/31468

**Comment by korewaChino** [comment]
> > Ultramarine Linux is a distribution based on Fedora which uses RPM packages, not DEB.
> 
> I am aware ostree is "Agnostic"?...
> 
> https://github.com/coreos/rpm-ostree
> 
> https://invent.kde.org/plasma/discover/-/merge_requests/109
> 
> https://discussion.fedoraproject.org/t/rpm-ostree-support-in-kde-discover/31468

And we use RPM-OSTree.

[literally](https://github.com/Ultramarine-Linux/ultramarine/issues/16#issuecomment-1605252595)

**Comment by rmnscnce** [comment]
In reply to @OpenOS-Project-Creator-Founder 

Of course it is distro-agnostic, even OSTree is used internally for Flatpak to deliver cross-distro applications for all Linux distributions out there. We are just alluding to the fact that we — as a distro, uses rpm-ostree because our distro is built entirely from RPM packages (naturally so, given that it is a remix of Fedora Linux).

**Comment by windowsboy111** [comment]
I would also like to draw your attention to the fact that our ISO images are already around 2 GB in size and I am afraid it is best not to add anything virtually useless to the ISO. Alternatively, you may use images from Fedora, and manually add the Ultramarine Linux and Terra repositories, then install the `ultramarine-release` package.
