### ISSUE TITLE
[BUG] Wallpaper set to default wallpaper when the dark theme is turned on

### ISSUE THREAD

**Issue by hakushigo** [Ultramarine-Linux/ultramarine#19]
**Describe the bug**
Wallpaper set to 'default' wallpaper when the dark theme is turned on

**To Reproduce**
1. Go to settings > desktop > apperance
2. Set the style to dark

**Expected behavior**
The wallpaper won't change when the dark theme turned on

**Screenshots**
![image](https://github.com/Ultramarine-Linux/ultramarine/assets/72906412/39ea2e1b-d197-4cfc-9406-ab03e89dc69f)
(The image when the dark theme turned off, this is my own custom wallpaper)

![image](https://github.com/Ultramarine-Linux/ultramarine/assets/72906412/3efd0b37-e5c6-437a-b5df-96008646e33c)
(The Image when the dark theme turned on, this is where the wallpaper is switched to)

**Desktop (please complete the following information):**
 - OS: Ultramarine Linux 38 (Tortuga)
 - Version 38

**Additional context**

**Comment by madonuko** [comment]
[I PR'ed a fix](https://github.com/elementary/switchboard-plug-pantheon-shell/pull/382) already but they haven't merged it. However, we applied the patch on Terra 39 and UM39, meaning this bug should be fixed once your system is up to date.
