### ISSUE TITLE
[FEATURE REQUEST] Enable Flathub by default

### ISSUE THREAD

**Issue by fariszr** [Ultramarine-Linux/ultramarine#2]
**Is your feature request related to a problem? Please describe.**
Currently, Fedora doesn't ship with Flathub enabled by default, which is annoying as any user will almost always want Flathub.

**Describe the solution you'd like**
Add Flathub by default

**Describe alternatives you've considered**
Adding Flathub manually, which defeats the “make sure your out-of-the-box experience is as smooth as it can be” goal of the distro

**Additional context**

**Comment by matteodev8** [comment]
Good idea, we will consider this

**Comment by korewaChino** [comment]
Flathub is already enabled by default. What are you talking about?

**Comment by matteodev8** [comment]
> Flathub is already enabled by default. What are you talking about?

It wasn't for me tho, I had to enable it manually but maybe this was an issue with the migration script.

**Comment by korewaChino** [comment]
Ah, yeah.

The migration script does not add Flathub, only RPMFusion. IIRC you have to install `ultramarine-repos` since the script fails to do that for whatever reason.

The script is supposed to only install the bare minimum for a valid Ultramarine install, but I guess we can add that too.

**Comment by korewaChino** [comment]
https://github.com/Ultramarine-Linux/website/commit/1958e73a6657ee87d01ff5d37d6d6f18d0659e36 Fixes this, closing this issue.
