### ISSUE TITLE
[BUG] Immutable - Su: Authentication failure (Root not enabled or created during setup)

### ISSUE THREAD

**Issue by Linux-Is-Best** [Ultramarine-Linux/ultramarine#20]
**Describe the bug**
During setup, the option to enable and create a root user is not presented. Subsequently, your user may have administrative privileges, such as SUDO, but you cannot access or log in as root. 

**To Reproduce**
1. Run the installer (see that root is not given as choice)
2. After install, open the terminal
3. Type in: "su"
4. Correct password will give you -  su: Authentication failure

**Expected behavior**
The ability to create a root user or login as root.

**Screenshots**
 n / a

**Desktop (please complete the following information):**
 - OS: Ultramarine Linux Flagship Edition -- Immutable build
 - Version

ostree-unverified-image:docker://ghcr.io/ultramarine-linux/ultramarine-flagship:39
                   Digest: sha256:7d046049304d6e12b1ee1e198913dd9dff960005a5f2a37fdc5cd19a0e9c405d
                Timestamp: 2023-11-25T06:08:46Z

**Additional context**

If by design (no root) the user should be presented with an alternative message.

**Comment by lleyton** [comment]
The root account not allowing password login is an intensional design decision for security, as most of the time, privileged actions run perfectly fine through polkit or sudo. However, if you do want to be able to log in as root or get a shell, `sudo su` should work, or you can set a root password using `sudo passwd`. If those don't work for some reason, that would be a bug.
