### ISSUE TITLE
[BUG] Immutable - Two (2) Wi-Fi icons in system tray

### ISSUE THREAD

**Issue by Linux-Is-Best** [Ultramarine-Linux/ultramarine#21]
**Describe the bug**
The system try visually displays two (2) Wi-Fi icons. Both of which are functional, but likely assigned to different network management interfaces. 

**To Reproduce**

1. Log into budgie (flagship)
2. Look at the taskbar (system try)
3. Visually see and interact with both

**Expected behavior**

For there to be only one (1).

**Screenshots**
![Snapshot_2023-11-26_16-15-37](https://github.com/Ultramarine-Linux/ultramarine/assets/61557098/4cb1c084-ce40-4854-9d26-d485e7916f34)

![Snapshot_2023-11-26_16-16-28](https://github.com/Ultramarine-Linux/ultramarine/assets/61557098/dd205209-7e45-4543-84f1-3875deb58195)

![Snapshot_2023-11-26_16-16-49](https://github.com/Ultramarine-Linux/ultramarine/assets/61557098/58f2f3d0-efcc-4dfe-ac26-a32e7c650bd1)

**Desktop (please complete the following information):**
 - OS: Ultramarine Linux Flagship Edition -- Immutable
 - Version 

● ostree-unverified-image:docker://ghcr.io/ultramarine-linux/ultramarine-flagship:39
                   Digest: sha256:7d046049304d6e12b1ee1e198913dd9dff960005a5f2a37fdc5cd19a0e9c405d
                Timestamp: 2023-11-25T06:08:46Z

**Additional context**
They both work, but they do have their own unique interface.

**Comment by lleyton** [comment]
I'm guessing that the first option is network-manager-applet, that shouldn't be enabled by default, so good catch.

**Comment by Linux-Is-Best** [comment]
This issue seems to be resolved -- Closing.
