### ISSUE TITLE
[BUG] Immutable:  Terminal command prompt caused GUI password prompt

### ISSUE THREAD

**Issue by Linux-Is-Best** [Ultramarine-Linux/ultramarine#26]
**Describe the bug**

The command in the terminal was:

rpm-ostree install neofetch

If a password was to be required, one would expect it in the terminal, not the GUI.

Note: screenshot included

**To Reproduce**

1. Open terminal
2. Type: rpm-ostree install neofetch
3. Press the "enter" key on your keyboard
4. See GUI prompt

**Expected behavior**

Expected everything to execute in the terminal.

**Screenshots**

[Snapshot_2023-11-26_15-29-12](https://github.com/Ultramarine-Linux/ultramarine/assets/61557098/62e70027-5df1-4afc-be8a-c52d98ee15e8)

**Desktop (please complete the following information):**
 - OS: Ultramarine Linux Flagship Edition -- Immutable
 - Version:
 - 
● ostree-unverified-image:docker://ghcr.io/ultramarine-linux/ultramarine-flagship:39
Digest: sha256:2a7d1d3ddb36a05d584ba56ff1d0ecd4112541c1d09d24d00d517e2bcbf18054
Timestamp: 2023-11-26T01:00:11Z

ostree-unverified-image:docker://ghcr.io/ultramarine-linux/ultramarine-flagship:39
Digest: sha256:7d046049304d6e12b1ee1e198913dd9dff960005a5f2a37fdc5cd19a0e9c405d
Timestamp: 2023-11-25T06:08:46Z

**Additional context**

I am not opposed to this, if by design. But I was not sure if this is intentional or not.

**Comment by korewaChino** [comment]
intended behaviour. rpm-ostree and even systemd calls polkit when user has no perms
