### ISSUE TITLE
[FYRA-343] [BUG] Immutable -- Firefox --  Widevine Content Decryption Module provided by Google Inc. will be installed shortly. 

### ISSUE THREAD

**Issue by Linux-Is-Best** [Ultramarine-Linux/ultramarine#29]
**Describe the bug**

In the immutable distro, Mozilla Firefox cannot fully install and enable Widevine when you check the setting to play DRM content.  Both in the Flatpak version or if you download the binary directly from Mozilla and extract it into your home folder.

**To Reproduce**
1. Open the Flatpak copy of Mozilla Firefox that is bundled with Ultramarine (or download the binary directly from Mozilla)
2. Go to setting
3. Enable play DRM content
4. View plugins in Firefox and see the error:  Widevine Content Decryption Module provided by Google Inc. will be installed shortly. 
5. Further confirm it isn't installed or working by visiting, Netflix

**Expected behavior**

For Firefox to be able to install the Widevine plugin.

**Screenshots**

N / A

**Desktop (please complete the following information):**
 - OS: Ultramarine Linux Flagship Edition
 - Version

● ostree-unverified-image:docker://ghcr.io/ultramarine-linux/ultramarine-flagship:39
                   Digest: sha256:ecdad29453f527a38cbea1347f39adabf58df2fce6dffa51fdee725817c51aef
                Timestamp: 2023-11-27T00:58:42Z
          LayeredPackages: neofetch

  ostree-unverified-image:docker://ghcr.io/ultramarine-linux/ultramarine-flagship:39
                   Digest: sha256:ecdad29453f527a38cbea1347f39adabf58df2fce6dffa51fdee725817c51aef
                Timestamp: 2023-11-27T00:58:42Z
          LayeredPackages: neofetch

**Additional context**

The issue does not impact Fedora Silver Blue or Universal Blue and a reinstallation of Ultramarine confirmed it was indeed Ultramarine

<sub>[FYRA-343](https://linear.app/fyra/issue/FYRA-343/[bug]-immutable-firefox-widevine-content-decryption-module-provided-by)</sub>

**Comment by Linux-Is-Best** [comment]
A follow-up:

Neither can Vivaldi Browser, which is based off of Chromium. 

It seems only Google Chrome itself, works in Ultramarine Linux Immutable.  -- That's not a good thing.

**Comment by lleyton** [comment]
Just for extra verification, could you test https://bitmovin.com/demos/drm within Vivaldi and Firefox?

**Comment by Linux-Is-Best** [comment]
> Just for extra verification, could you test https://bitmovin.com/demos/drm within Vivaldi and Firefox?

Confirmed the issue is genuine.  But the issue does not impact Ultramarine Linux alone. I was testing another development, and discovered this impacts Universal Blue too https://mstdn.social/@Linux_Is_Best/111497127545008050

**Comment by lleyton** [comment]
Thanks for the additional info, we'll get on it ASAP.

**Comment by Linux-Is-Best** [comment]
Closing this. 

Why?  It was a network issue and nothing to do with the distro. Upon changing my IP, everything installed fine.
