### ISSUE TITLE
[FEATURE REQUEST] Add option to install closed source drivers and codecs automatically in the installer

### ISSUE THREAD

**Issue by FarisZR** [Ultramarine-Linux/ultramarine#3]
**Is your feature request related to a problem? Please describe.**
Fedora doesn't have an option to install closed source drivers and codecs similar to Ubuntu, which makes it a bit difficult to use for new users.

**Describe the solution you'd like**
An option to install closed source drivers like NVIDIA and codecs in the installer.

**Describe alternatives you've considered**
Manually installing drivers which defeats the “make sure your out-of-the-box experience is as smooth as it can be” goal of the distro

**Additional context**
I think this distro can benefit from Ubuntu's driver installation scripts.

**Comment by trobonox** [comment]
We have not considered integration into the installer yet, but we have a welcome application planned, which is run post-install and gives you options to install drivers, codecs, desktop environments and other useful packages.

Thanks for your suggestion, we will evaluate if the welcome app is enough or we should aim for the installer integration.

**Comment by korewaChino** [comment]
Integrating an option to install closed-source drivers would require writing a module for Anaconda, which we can't afford to do right now.

However we are planning to add an option into the OOBE for this.

**Comment by korewaChino** [comment]
We are working on this

https://github.com/Ultramarine-Linux/stellar
