### ISSUE TITLE
desktop disk images for aarch64

### ISSUE THREAD

**Issue by kerry-s** [Ultramarine-Linux/ultramarine#30]
all the aarch64 images do not work on my rpi4-4gb.
stock fedora 39 boots and works fine.

**Comment by madonuko** [comment]
Is there a boot entry? Can you load the bootloader? Does init run?

**Comment by kerry-s** [comment]
it's not even detected.
i think because it's a live image, in fedora we use the raw.xz.

i currently did a clean fedora 39 install and i'm running the
bash <(curl -s https://ultramarine-linux.org/migrate.sh)

but my internet is slow so it's still at "+ sudo dnf update -y", looks like i'm in for a wait.

**Comment by lleyton** [comment]
Have you been using the images on https://images.fyralabs.com/images/ultramarine/39/ ?

I'm pretty sure those should work, if not, I'll do some investigation.

**Comment by korewaChino** [comment]
cannot reproduce, we have raw images

**Comment by kerry-s** [comment]
> Have you tested the images on https://images.fyralabs.com/images/ultramarine/39/ ?
> 
> I'm pretty sure those should work, if not, I'll do some investigation.

yes, i tried that 1, it just gave me a command line and i didn't know the login.

**Comment by kerry-s** [comment]
i've got ultramarine up and running using the
bash <(curl -s https://ultramarine-linux.org/migrate.sh)

the grub boot still says fedora linux, but after that is all ultramarine.
i had to install pop shell my shelf.
other than those issues i haven't come across any others yet, i'm still setting up.

**Comment by kerry-s** [comment]
> cannot reproduce, we have raw images

i grabbed all the images here
https://ultramarine-linux.org/um39-arm/

there are no raw images there

**Comment by korewaChino** [comment]
> > Have you tested the images on https://images.fyralabs.com/images/ultramarine/39/ ?
> > I'm pretty sure those should work, if not, I'll do some investigation.
> 
> yes, i tried that 1, it just gave me a command line and i didn't know the login.

the login is ultramarine:ultramarine

**Comment by madonuko** [comment]
The raw disk images are available on the [download page](https://ultramarine-linux.org/download/), take a look at the section "Disk images".

We are sorry for any confusions regarding the raw disk images, and we will make the following changes:
- We will provide more thorough documentations regarding the raw disk images
- We will update the website to entail a smoother experience, which includes
  - changing the section title to "Raw disk images" instead of just "Disk images" for any confusion
  - adding the link in the aarch64 section
  - specifying that these are raw images for rpis
  
If you have any further suggestions or feedback, please don't hesitate to respond to this thread.

**Comment by kerry-s** [comment]
> The raw disk images are available on the [download page](https://ultramarine-linux.org/download/), take a look at the section "Disk images".

as said i tried that image, it booted to command line login.
i couldn't find the user name or password anywhere to get into it. so it just left me stuck.
i tried fedora/fedora, root/1234, ultramarine/1234, etc ....

**Comment by kerry-s** [comment]
> > > Have you tested the images on https://images.fyralabs.com/images/ultramarine/39/ ?
> > > I'm pretty sure those should work, if not, I'll do some investigation.
> > 
> > 
> > yes, i tried that 1, it just gave me a command line and i didn't know the login.
> 
> the login is ultramarine:ultramarine.
> 
> all disk images are minimal builds, it does not contain any desktop environment

strange, i'm pretty sure i tried that.
i may have been locked out after 3 failures.

**Comment by kerry-s** [comment]
> all disk images are minimal builds, it does not contain any desktop environment

shame, not going to be to popular with people not familiar with cli/linux
i'm an old foggy so been in the game awhile, cli is not an issue for me.

suggest at least the flagship budgie or gnome for people who want a wayland desktop.

i'm mainly a gnome user

**Comment by korewaChino** [comment]
> > The raw disk images are available on the [download page](https://ultramarine-linux.org/download/), take a look at the section "Disk images".
> 
> as said i tried that image, it booted to command line login. i couldn't find the user name or password anywhere to get into it. so it just left me stuck. i tried fedora/fedora, root/1234, ultramarine/1234, etc ....

the login is `ultramarine:ultramarine`.

Both the username and password is `ultramarine`

**Comment by kerry-s** [comment]
i'm more interested in desktop install.
i was successful doing the fedora 39 install + the bash migration script.
![Screenshot from 2023-11-29 08-37-58](https://github.com/Ultramarine-Linux/ultramarine/assets/40045415/4b875115-03ee-4394-bc71-6d7bdd3e778a)

**Comment by nothingneko** [comment]
I'm sorry for the lack of information and we'll be updating our docs in the near future to reflect the way raw images work. On the note of your feedback, we'll look into providing a desktop by default for Raspberry Pi, thank you!

**Comment by kerry-s** [comment]
that would be great.
with the current gen of rpi's being more powerful, the most common use is as a desktop system.

i like ultramarine cause it makes fedora simple to get up and running fast.
it's also more up to date compared to other distros.

i did try all the versions on my lenovo laptop and currently have the same gnome setup as my rpi. it has a touch screen and the mousepad is not supported under linux, gnome seems to be the best so far for a touch screen setup. X11 just moves the mouse cursor around the screen, don't like that which is why i prefer wayland.

anyways, you can close this as i did get it installed using the migration script.

if it comes up in the raspberry forums i'll suggest that for people wanting ultramarine. fedora is not really popular as the setup requires a bit of post install effort to have a fully functioning system.

also there was a kernel update, grub now shows ultramarine instead of fedora.
i have grub timeout set to 0, so really didn't care what the boot said.
now everything reads ultramarine.
i think it didn't change before was because of uboot used for rpi.

**Comment by muhdsalm** [comment]
The new XFCE edition might be a good choice for this image due to it's low performance overhead.

**Comment by nothingneko** [comment]
we’re going to be providing a raw image of all desktops, not just Xfce :3

**Comment by lleyton** [comment]
This is completed in 40!
