### ISSUE TITLE
[BUG] Excessive password prompts

### ISSUE THREAD

**Issue by rthrejheytjyrtj545** [Ultramarine-Linux/ultramarine#31]
In the following situations: GNOME Software attempts to check for updates or manage applications, including immediately after logging into a session; actions with OSTree; every time sudo and pkexec without timeout.

This is the minimum that is present in the atomic version of Ultramarine Gnome 39, but nevertheless is not observed in Fedora Silverblue 39.

**Comment by lleyton** [comment]
This should be resolved now. Can you upgrade your system and let me know if the issue is resolved?

**Comment by Linux-Is-Best** [comment]
I am looking forward to hearing @rthrejheytjyrtj545 report back, because this seems to be resolved on my end too. Although, I was using the flagship (Budgie desktop).

**Comment by lleyton** [comment]
I'm going to assume that this is fixed, based on @Linux-Is-Best's comments and my own testing.
