### ISSUE TITLE
[POST LOGS/REPORT HERE] [BUG] Cannot connect to encrypted WIFI on Budgie/Flagship

### ISSUE THREAD

**Issue by madonuko** [Ultramarine-Linux/ultramarine#32]
# We need more diagnostics

If you are having issues with WIFI connections on Ultramarine 39 Flagship Edition (Budgie Desktop Environment), you may post your logs and report here.

# Workaround
- try using the "Connect to hidden WiFi" button, accessible via Budgie Control Center.
- try using `nmcli` instead, you may look at a quick guide [here](https://www.makeuseof.com/connect-to-wifi-with-nmcli/).

# How to Report
## Logs
**We prefer pastebins. Do NOT spam the logs here directly.**
- logs by starting WIFI settings in terminal
- `journalctl -u NetworkManager.service --no-pager`
- `nmcli dev`
- provide specs for your Wireless Network Interface Card (NIC)
- if possible, test if issue exists on other spins and distros with Budgie

## Other places to report
- [Thread on Discord](https://discord.com/channels/879284135779266560/1183083924310736947)
- [Reddit](https://www.reddit.com/r/)
- Tag `@ultramarine@fedi.fyralabs.com` on [Mastodon/Fediverse](https://fedi.fyralabs.com/@ultramarine)

### Reddit
- https://www.reddit.com/r/ultramarine/comments/18c5am4/red_exclamation_mark_next_to_wifi/
### Discord
- https://discord.com/channels/879284135779266560/979378501390057482/1182596475893596170
- https://discord.com/channels/879284135779266560/979378501390057482/1171955477668712508
- https://discord.com/channels/879284135779266560/880699758723874816/1183074783437524992

# Current speculations
- probably an upstream issue
- happens only with certain devices / NICs
- happens only on Flagship/Budgie
- happens only on UM 39

**Comment by meghan06** [comment]
https://pastebin.com/mDvDLaei

Logs from Arch Linux for reference

**Comment by Zyonin** [comment]
https://pastebin.com/Sq5xWJiy

Network controller: Realtek Semiconductor Co., Ltd. RTL8822CE 802.11ac PCIe Wireless Network Adapter

I can see the networks, can even click on the network but I don't get a dialogue for entering the password.   The gear icon also disappears after a second or two and the list resets.   Those is both through the systray applet and Budgie Control Center.

Note:  I was able to connect through the CLI using nmcli.    I had been able to connect using the GUI while using Ultramarine Linux 38 Flagship Edition.    I don't have any network connection issues with other distros though I have not tested a distro with  the same version of Budgie DE.

**Comment by madonuko** [comment]
> https://pastebin.com/Sq5xWJiy

@Zyonin you are only partially showing the logs (both the width and the height). Try `journalctl -u --no-pager NetworkManager.service` instead. Thanks.

**Comment by Linux-Is-Best** [comment]
No noticeable issue, to my knowledge. Only a repeated warning. 

`<warn>  [1702268699.4801] ndisc[0x55f11e6cdde0,"wlp2s0"]: solicit: failure sending router solicitation: Operation not permitted (1)`

Continuously repeated.   Only that 1st set of numbers changes, the rest is the same.  So more accurately:

`<warn>  [random numbers here] ndisc[0x55f11e6cdde0,"wlp2s0"]: solicit: failure sending router solicitation: Operation not permitted (1)`

```
wlp2s0          wifi       connected               Zelda      
lo              loopback   connected (externally)  lo         
wgivpn          wireguard  connected (externally)  wgivpn     
p2p-dev-wlp2s0  wifi-p2p   disconnected            -- 
```

![f1f24da109e828fb](https://github.com/Ultramarine-Linux/ultramarine/assets/61557098/fe5a7b97-be66-4fd2-9db6-35b683d3a978)

**Comment by cperez616** [comment]
> No noticeable issue, to my knowledge. Only a repeated warning.
> 
> `ultramarine NetworkManager[1179]: <warn> [1702268699.4801] ndisc[0x55f11e6cdde0,"wlp2s0"]: solicit: failure sending router solicitation: Operation not permitted (1)`
> 
> Continuously repeated. Only that 1st set of numbers changes, the rest is the same. So more accurately:
> 
> `ultramarine NetworkManager[1179]: <warn> [random numbers here] ndisc[0x55f11e6cdde0,"wlp2s0"]: solicit: failure sending router solicitation: Operation not permitted (1)`
> 
> ```
> wlp2s0          wifi       connected               Zelda      
> lo              loopback   connected (externally)  lo         
> wgivpn          wireguard  connected (externally)  wgivpn     
> p2p-dev-wlp2s0  wifi-p2p   disconnected            -- 
> ```
> 
> ![f1f24da109e828fb](https://private-user-images.githubusercontent.com/61557098/289425707-fe5a7b97-be66-4fd2-9db6-35b683d3a978.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI4NDc5NzIsIm5iZiI6MTcwMjg0NzY3MiwicGF0aCI6Ii82MTU1NzA5OC8yODk0MjU3MDctZmU1YTdiOTctYmU2Ni00ZmQyLTlkYjYtMzViNjgzZDNhOTc4LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE3VDIxMTQzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIyYTFiOGNmZjA0MmYwY2QyN2FjNWFmYWY4MjkzNzkzYTAzNDRiODM4ODZmN2ZiMTgyMWY4NjkwZjFkYzlmMWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5PHjAwjBZyA8hZK48jP1rsYH_zD1DqWSJGvYjHE6HRQ)

Hey, the same happened to me. I got frustrated and gave up. Did you find a fix? I can't find anything on the Internet about this.

**Comment by lleyton** [comment]
This one should be fixed now in the latest ISOs, please reopen if this appears again.
