### ISSUE TITLE
[BUG] Failed to start auditd.service - Security Auditing Service.

### ISSUE THREAD

**Issue by alexanderlavrenko** [Ultramarine-Linux/ultramarine#36]
Here's what I get after boot and type `sudo journalctl -p 3 -xb`:

> 
> Feb 19 10:26:49 ultramarine kernel: x86/cpu: SGX disabled by BIOS.
> Feb 19 10:26:49 ultramarine systemd-vconsole-setup[261]: /usr/bin/setfont fai>
> Feb 19 10:26:51 ultramarine systemd-vconsole-setup[566]: /usr/bin/setfont fai>
> Feb 19 10:27:06 ultramarine auditd[1190]: Could not open dir /var/log/audit (>
> Feb 19 10:27:06 ultramarine systemd[1]: Failed to start auditd.service - Secu>
> ░░ Subject: A start job for unit auditd.service has failed
> ░░ Defined-By: systemd
> ░░ Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
> ░░
> ░░ A start job for unit auditd.service has finished with a failure.
> ░░
> ░░ The job identifier is 320 and the job result is failed.
> Feb 19 10:27:06 ultramarine auditd[1201]: Could not open dir /var/log/audit (>
> Feb 19 10:27:06 ultramarine systemd[1]: Failed to start auditd.service - Secu>
> ░░ Subject: A start job for unit auditd.service has failed
> ░░ Defined-By: systemd
> ░░ Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
> ░░
> ░░ A start job for unit auditd.service has finished with a failure.
> ░░
> ░░ The job identifier is 445 and the job result is failed.
> Feb 19 10:27:06 ultramarine auditd[1204]: Could not open dir /var/log/audit (>
> Feb 19 10:27:06 ultramarine systemd[1]: Failed to start auditd.service - Secu>
> ░░ Subject: A start job for unit auditd.service has failed
> ░░ Defined-By: systemd
> lines 1-25...skipping...
> Feb 19 10:26:49 ultramarine kernel: x86/cpu: SGX disabled by BIOS.
> Feb 19 10:26:49 ultramarine systemd-vconsole-setup[261]: /usr/bin/setfont failed with exit status 71.
> Feb 19 10:26:51 ultramarine systemd-vconsole-setup[566]: /usr/bin/setfont failed with exit status 71.
> Feb 19 10:27:06 ultramarine auditd[1190]: Could not open dir /var/log/audit (No such file or directory)
> Feb 19 10:27:06 ultramarine systemd[1]: Failed to start auditd.service - Security Auditing Service.
> ░░ Subject: A start job for unit auditd.service has failed
> ░░ Defined-By: systemd
> ░░ Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
> ░░
> ░░ A start job for unit auditd.service has finished with a failure.
> ░░
> ░░ The job identifier is 320 and the job result is failed.
> Feb 19 10:27:06 ultramarine auditd[1201]: Could not open dir /var/log/audit (No such file or directory)
> Feb 19 10:27:06 ultramarine systemd[1]: Failed to start auditd.service - Security Auditing Service.
> ░░ Subject: A start job for unit auditd.service has failed
> ░░ Defined-By: systemd
> ░░ Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
> ░░
> ░░ A start job for unit auditd.service has finished with a failure.
> ░░
> ░░ The job identifier is 445 and the job result is failed.
> Feb 19 10:27:06 ultramarine auditd[1204]: Could not open dir /var/log/audit (No such file or directory)
> Feb 19 10:27:06 ultramarine systemd[1]: Failed to start auditd.service - Security Auditing Service.
> ░░ Subject: A start job for unit auditd.service has failed
> ░░ Defined-By: systemd
> ░░ Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
> ░░
> ░░ A start job for unit auditd.service has finished with a failure.
> ░░
> ░░ The job identifier is 449 and the job result is failed.
> Feb 19 10:27:06 ultramarine auditd[1247]: Could not open dir /var/log/audit (No such file or directory)
> Feb 19 10:27:07 ultramarine systemd[1]: Failed to start auditd.service - Security Auditing Service.
> ░░ Subject: A start job for unit auditd.service has failed
> ░░ Defined-By: systemd
> ░░ Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
> ░░
> ░░ A start job for unit auditd.service has finished with a failure.
> ░░
> ░░ The job identifier is 565 and the job result is failed.
> Feb 19 10:27:07 ultramarine auditd[1445]: Could not open dir /var/log/audit (No such file or directory)
> Feb 19 10:27:07 ultramarine systemd[1]: Failed to start auditd.service - Security Auditing Service.
> ░░ Subject: A start job for unit auditd.service has failed
> ░░ Defined-By: systemd

so the problem is that auditd.service is not working

**Steps that DID NOT help:**
- Following [HOWTO Fedora Enable Auditing](https://github.com/linux-audit/audit-documentation/wiki/HOWTO-Fedora-Enable-Auditing)
- Creating audit.log with 'sudo touch /var/log/audit/audit.log'

Any idea why does it fail to start auditd.service and how to fix it?

**Desktop (please complete the following information):**
 - OS: [e.g. Ultramarine Linux KDE Edition]
 - Version [e.g. 39]

**Additional context**
It happens regardless of KDE and I spotted this on Hyprland. Both when I boot into KDE or Hyprland then I get this message.

**Comment by madonuko** [comment]
Please complete the information on the GitHub issue template, including but not limited to your Desktop information.

Also, do you happen to be on Immutable/Atomic versions of Ultramarine Linux? If you don't know what I'm talking about here, then you're probably not on Atomic.

**Comment by alexanderlavrenko** [comment]
> Please complete the information on the GitHub issue template, including but not limited to your Desktop information.
> 
> Also, do you happen to be on Immutable/Atomic versions of Ultramarine Linux? If you don't know what I'm talking about here, then you're probably not on Atomic.

What kind of additional information could help?

I don't know what you mean by Immutable/Atomic versions, I've downloaded Ultramarine Linux (KDE Edition) ISO from official website.

**Comment by madonuko** [comment]
![image](https://github.com/Ultramarine-Linux/ultramarine/assets/48051237/4d1239da-75fe-4f19-9815-e4c9d7a93ebf)
You need to provide your edition (which I know is KDE from other text) and your release version (which I don't know)

The latest release version as of now is 39. You can check which release version you are on by going to KDE System Settings → System Administration → About this System.

I'm personally on Ultramarine 39 KDE and I cannot reproduce this issue.

**Comment by alexanderlavrenko** [comment]
> ![image](https://private-user-images.githubusercontent.com/48051237/305996660-4d1239da-75fe-4f19-9815-e4c9d7a93ebf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgzNTg2NTEsIm5iZiI6MTcwODM1ODM1MSwicGF0aCI6Ii80ODA1MTIzNy8zMDU5OTY2NjAtNGQxMjM5ZGEtNzVmZS00ZjE5LTk4MTUtZTRjOWQ3YTkzZWJmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE5VDE1NTkxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMxOTc3ZmFjMmFlNTQ1ODZkOWIwZGQ4MzJiMDE5MTZlOGM1NjFlMWUzOTIyOTVkODc1N2Q1NzdmYTE0ZDY3ZDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ahULHr-tYg6pVnRVJTgzhpZp_CC5-aXsIrP80Rg9UB0) You need to provide your edition (which I know is KDE from other text) and your release version (which I don't know)
> 
> The latest release version as of now is 39. You can check which release version you are on by going to KDE System Settings → System Administration → About this System.
> 
> I'm personally on Ultramarine 39 KDE and I cannot reproduce this issue.

I'm on Ultramarine 39 KDE as well, and it's up to date. I see it just after boot in journalctl. 

Maybe it has something to do with my installation but it doesn't seem relevant but I hope so.

I'll do complete re-install next week probably, and then will tell if I found it again.

**Comment by alexanderlavrenko** [comment]
> Fonts are white and everything looks right and clear without having to manually change certain colours. At least supposedly!
> 
> We've tested our ISOs for these kinds of theme customisations before release and they worked fine.
> 
> Without any further information I'm afraid the theme issue and the auditd issue can't be reproduced easily… I reckon this is an issue specific to your installation somehow (maybe you messed up something unorthodox / peculiar, who knows?), so you probably will fancy a reinstallation.
> 
> Don't worry, I'll keep this issue open, you may hit us at any time once you reinstalled; hope everything goes well!

Check my explanation about dark theme effect above, there's no problem with KDE itself.
`audit` problem is a mystery for now but I'll tell if it's there after re-installation.
Thanks.
