### ISSUE TITLE
website - invalid url

### ISSUE THREAD

**Issue by ghost** [Ultramarine-Linux/ultramarine#37]
The website still lists v36 to download https://ultramarine-linux.org/download/

Technically, v37 is available, but was end of life a while ago, if I am not mistaken. So it would be OK to remove the URL and the ISOs from the server.

**Comment by Linux-Is-Best** [comment]
I think you misunderstood. There is NO v36 to download. v36 was removed from the server.

v37 was a suggestion to do the same.

To resolve this, either remove the v36 url or add back the v36 files (ISOs)

**Comment by Linux-Is-Best** [comment]
![Screenshot_20240313-143130](https://github.com/Ultramarine-Linux/ultramarine/assets/61557098/69be33c6-c3c4-4072-924a-75f42fd838d4)

There is nothing to download.

**Comment by lleyton** [comment]
Ah right, this was pre-infra migration. Do we have the ISOs laying around or?

Additionally, we should probably put an EOL banner on those but that's another thing.

**Comment by nothingneko** [comment]
I can't find any copies of them, and if we don't have anything other than team member's devices I think we should just remove them

**Comment by madonuko** [comment]
I have only GNOME 36

**Comment by muhdsalm** [comment]
So... what do we want to do about this? Remove the page?

**Comment by lleyton** [comment]
We pruned the EOL entries
