### ISSUE TITLE
[FEATURE REQUEST] Enable DNF fastestmirror and increase max_parallel_download to 10 by default

### ISSUE THREAD

**Issue by fariszr** [Ultramarine-Linux/ultramarine#4]
**Is your feature request related to a problem? Please describe.**
One of the common issues with Fedora is slow download speeds of DNF.
Enabling Fastest mirror and increasing max parallel downloads improves the speed noticeably most of the time.

**Describe the solution you'd like**
Enable DNF fastestmirror and increase max_parallel_download to 10 by default

**Describe alternatives you've considered**
Being stuck with slow speeds or doing it manually, which is not a good first-run experience

**Comment by jadeastar** [comment]
Not an Ultramarine dev, but that many parallel downloads screws performance and is bad for people with low bandwidth connections. 3 is a better value.

**Comment by korewaChino** [comment]
fastestmirror kinds of slow down the initial metadata fetch by doing a speedtest on all repos which makes DNF feel even slower imo. I don't think we should enable fastestmirror.

Plus, fastest mirror doesn't mean the best mirror.

**Comment by fariszr** [comment]
> fastestmirror kinds of slow down the initial metadata fetch by doing a speedtest on all repos 
Only for the first time from my usage, Then it just uses the same mirror every time you update.

**Comment by fariszr** [comment]
> > > fastestmirror kinds of slow down the initial metadata fetch by doing a speedtest on all repos
> > 
> > 
> > Only for the first time from my usage, Then it just uses the same mirror every time you update.
> 
> But then, your repos will become out of sync with upstream since that fastest mirror probably won't be the most up to date one.

These are official Fedora mirrors, so they are always updated

**Comment by windowsboy111** [comment]
An option for `max_parallel_downloads` and `fastestmirror` has been added to [umtweaks](https://github.com/Ultramarine-Linux/ultramarine-tweaks/). Note that umtweaks is not yet in Ultramarine Linux repos.

`max_parallel_downloads` is still 3 by default.

The issue will be closed for the time being; you may reopen it if you have any suggestions regarding this enhancement. Thank you for your time and suggestion.
