### ISSUE TITLE
[FEATURE REQUEST] Enable ZSH shell history by default

### ISSUE THREAD

**Issue by glexposito** [Ultramarine-Linux/ultramarine#5]
Enable ZSH history by default. I would like to have the ZSH shell history enabled by default.

I found the [pkg-ultramarine-shell-config](https://github.com/Ultramarine-Linux/pkg-ultramarine-shell-config) repo in the project and I saw that the history option was added there. Was it added to cover the shell configuration in further releases? Just to check :) (I have no development experience in Linux distros)

**Comment by korewaChino** [comment]
yeah, should be fixed.
