### ISSUE TITLE
[Feature] Include the Geary email client in the GNOME edition's default app selection

### ISSUE THREAD

**Issue by ghost** [Ultramarine-Linux/ultramarine#62]
### Describe the related problem / the feature request

This is in order to save time so that when people add their Email account in GOA, they start receiving mail in an email client immediately and directly without having to install and configure an email client.

### Describe a solution and how it solves the above problem
_Given._

### Alternatives you've considered

Include Evolution as it also adds email accounts in GOA automatically but remember that it doesn't follow the HIG as closely.

### Additional Context
I am using the GNOME edition (Ultramarine 40).

**Comment by nothingneko** [comment]
Let's do it
