### ISSUE TITLE
[Feature] Enable FZF command history search with Ctrl-R

### ISSUE THREAD

**Issue by ghost** [Ultramarine-Linux/ultramarine#65]
**Demo:**
https://github.com/user-attachments/assets/9d377960-4dd6-437a-bc99-0f5551b2d7ac

**How to have it enabled OOTB (for zsh):**
Have FZF be installed OOTB and have `source /usr/share/fzf/shell/key-bindings.zsh` in the `.zshrc` in `/etc/skel`

**Comment by korewaChino** [comment]
can you make a PR for this in https://github.com/Ultramarine-Linux/packages

**Comment by ghost** [comment]
> can you make a PR for this in https://github.com/Ultramarine-Linux/packages


I don't know how to exactly.

**Comment by ghost** [comment]
> can you make a PR for this in https://github.com/Ultramarine-Linux/packages

Can you guide me (or do it yourself)?

**Comment by korewaChino** [comment]
> > can you make a PR for this in https://github.com/Ultramarine-Linux/packages
> 
> Can you guide me (or do it yourself)?

I suggest you check out the ultramarine-shell-config package in the packages repo, check [this](https://developer.fyralabs.com/terra/contributing) guide on how to make patches.

All you should do is simply add the source line to the [zsh config](https://github.com/Ultramarine-Linux/packages/blob/um41/ultramarine/shell-config/ultramarine-shell.zsh) and require fzf in the spec.

**Comment by ghost** [comment]
> > > can you make a PR for this in https://github.com/Ultramarine-Linux/packages
> > 
> > 
> > Can you guide me (or do it yourself)?
> 
> I suggest you check out the ultramarine-shell-config package in the packages repo, check [this](https://developer.fyralabs.com/terra/contributing) guide on how to make patches.
> 
> All you should do is simply add the source line to the [zsh config](https://github.com/Ultramarine-Linux/packages/blob/um41/ultramarine/shell-config/ultramarine-shell.zsh) and require fzf in the spec.

I have made the edits in my clone of the repository, but please excuse my ignorance, as I'm new to this: how do I commit and push now? I tried running this
 `git push Ultramarine-Linux/packages w/shell-config
` 
but it gives this error:
`fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
`

**Comment by korewaChino** [comment]
you have to enter the git repository using `cd`, fork the repository and set the remote origin URL to your fork
```bash
cd $git_repo
git remote set-url origin <your_fork_here>

git add .
git commit # edit your commit messages

git push
```
then make PR on GitHub

**Comment by ghost** [comment]
> you have to enter the git repository using `cd`, fork the repository and set the remote origin URL to your fork
> 
> ```shell
> cd $git_repo
> git remote set-url origin <your_fork_here>
> 
> git add .
> git commit # edit your commit messages
> 
> git push
> ```
> 
> then make PR on GitHub

Where do I need to make this pull request? On the pull requests link on the fork repo's homepage or on the `ultramarine-linux/packages` repository's homepage?

**Comment by madonuko** [comment]
> Where do I need to make this pull request? On the pull requests link on the fork repo's homepage or on the ultramarine-linux/packages repository's homepage?

I think they are the same thing, if you click contribute / create pull request in your own repo it just redirects to ours.
