### ISSUE TITLE
[BUG] DNF version reverts to DNF4 after upgrade to UM41

### ISSUE THREAD

**Issue by clintre** [Ultramarine-Linux/ultramarine#66]
### Summary

I did the in-place upgrade from UM40 (KDE) to UM41. After the upgrade, I noticed the DNF5 commands I would use would fail. So I did a DNF --version, and it came back as 4.21.1. I was able to reproduce this issue by doing an upgrade of 40-41 on another test system. DNF5 is installed and I can run dnf5 commands. 

I did a reinstallation of dnf5 and it resolved the issue. This issue is not present on a system where I did a clean installation of UM41. 
![UM41-upgrade-dnf4](https://github.com/user-attachments/assets/29749b2e-684d-4f27-a041-76e3a1c37ff9)

### Steps to Reproduce

1. Upgrade from UM40 to UM41
2. dnf --version will show 4.21.1

### Possible Solutions

Reinstall dnf5 and then the dnf --version once again shows as 5.2.6.2

### Release Version

41

### Edition / Desktop Environment / Hardware

KDE Plasma

### Checklist

- [X] I've checked for duplicates in this repository. (not required)
- [ ] I'm using the immutable/atomic version. (i.e. I think this issue might be specific to immutable.)
- [X] This issue is not reproducible on Fedora Linux.
- [ ] This issue is not reproducible on other Linux distros.

**Comment by madonuko** [comment]
Very interesting, so before reinstallation of `dnf5`, `dnf` points to `dnf-3`,  but after reinstallation it points to `dnf5`… Sounds like an issue from `dnf5-default-package-manager` applying the post uninstall scriptlets after installation of `dnf5` during upgrade…

**Comment by madonuko** [comment]
I assume this is fixed (at least it works during my upgrades on my machine)
Thank you for the bug report
