### ISSUE TITLE
[FEATURE REQUEST] Text color in installer

### ISSUE THREAD

**Issue by sebastiaanfranken** [Ultramarine-Linux/ultramarine#7]
I've installed UM in a virtual machine on my main Fedora rig to see how it's shaping up. So far it's impressed me, but one thing stuck out a bit: the text color on the installer makes it hard to read certain things. A error / darker text is very hard to read on the dark background of the installer.

Maybe see if you can lighten that colour a bit in the theme you use on Anaconda? I know what the error stated (no disk selected during install) so for me it's not really a big issue, but I can see it being a frustrating thing for new users.

**Comment by nothingneko** [comment]
Closing ahead of UM40. This is also fixed in UM39
