### ISSUE TITLE
[BUG] Display settings don't stick on the Pantheon Spin

### ISSUE THREAD

**Issue by amminadabz** [Ultramarine-Linux/ultramarine#8]
Changes to display settings (layout of displays, disabling a display, etc) made in either Switchboard or Gnome Control Center will revert unprompted after a minute or two. The "Does this configuration look right?" window is never shown on either display.

**Comment by amminadabz** [comment]
If it helps, an equivalent xrandr command changing the display position does not have this problem.

**Comment by riffer33** [comment]
I'll note that the same thing happens when you install the Pantheon DE to Fedora directly.

**Comment by muhdsalm** [comment]
> I'll note that the same thing happens when you install the Pantheon DE to Fedora directly.

Stock Fedora or Stock Ultramarine?

**Comment by lleyton** [comment]
Closing, Pantheon spin is currently discontinued in 40.
