### ISSUE TITLE
[BUG] Flatpak installs fail

### ISSUE THREAD

**Issue by amminadabz** [Ultramarine-Linux/ultramarine#9]
**Describe the bug**
Attempting to install a flatpak app through terminal or Elementary Appcenter yields the error:
`error: Failed to install: Error deploying: Timeout was reached`

**To Reproduce**
1. Run `flatpak install spotify`
2. Wait for download to finish
3. See error

**Expected behavior**
The dang thing to install correctly

**Screenshots**
![Screenshot from 2022-08-18 17 41 27](https://user-images.githubusercontent.com/51542239/185724398-fbe2df47-bd9f-4a98-a659-7fbd6c507567.png)

**Desktop (please complete the following information):**
 - OS: Ultramarine Linux Pantheon Edition
 - Version 36

**Comment by korewaChino** [comment]
@PizzaLovingNerd

**Comment by korewaChino** [comment]
The patch should be available soon at https://lapis.ultramarine-linux.org/koji/taskinfo?taskID=3935.
You should be able to just install `flatpak-selinux-fix` to apply it.
